Favor-Gift-Reminder/Favor-Server

favor/src/main/java/com/favor/favor/User/UserController.java
favor/src/main/java/com/favor/favor/friend/FriendRepository.java
favor/src/main/java/com/favor/favor/reminder/ReminderController.java
favor/src/main/java/com/favor/favor/reminder/ReminderService.java
favor/src/main/java/com/favor/favor/user/UserController.java

- #2
- 회원친구의 기념일을 유저의 리마인더에 추가하는 기능 구현

[Feat] 기념일을 리마인더에 추가하는 기능

---

favor/src/main/java/com/favor/favor/User/ProfileDto.java
favor/src/main/java/com/favor/favor/User/SignUpDto.java
favor/src/main/java/com/favor/favor/User/UserUpdatePasswordRequestDto.java
favor/src/main/java/com/favor/favor/User/UserUpdateRequestDto.java
favor/src/main/java/com/favor/favor/anniversary/AnniversaryRequestDto.java
favor/src/main/java/com/favor/favor/anniversary/AnniversaryResponseDto.java
favor/src/main/java/com/favor/favor/anniversary/AnniversaryUpdateRequestDto.java
favor/src/main/java/com/favor/favor/common/DefaultResponseDto.java
favor/src/main/java/com/favor/favor/friend/FriendResponseDto.java
favor/src/main/java/com/favor/favor/friend/account/FriendUserRequestDto.java
favor/src/main/java/com/favor/favor/friend/noAccount/FriendRequestDto.java
favor/src/main/java/com/favor/favor/friend/noAccount/FriendUpdateRequestDto.java
favor/src/main/java/com/favor/favor/gift/GiftRequestDto.java
favor/src/main/java/com/favor/favor/gift/GiftUpdateRequestDto.java
favor/src/main/java/com/favor/favor/reminder/ReminderRequestDto.java
favor/src/main/java/com/favor/favor/reminder/ReminderUpdateRequestDto.java

#1 #5 
- @NoArgsConstructor(access = AccessLevel.PROTECTED) 를
- @NoArgsConstructor 로 변경

DTO 기본생성자 수정

---

favor/build.gradle
favor/src/main/java/com/favor/favor/anniversary/AnniversaryRequestDto.java

- #9 
- 기념일 생성 시 isPinned 멤버에 false 자동 추가

기념일 생성 시 isPinned 멤버에 false 자동 추가

---

favor/.gitignore
favor/src/main/resources/application.yml

- #4 
- gitignore에서 .properties ignore 삭제
- resources/application.yml 새로 생성하여 환경변수 처리 완료
- 환경변수 처리 및 내용 공유 완료

[Style] gitignore 설정

---

favor/src/main/java/com/favor/favor/User/UserService.java
favor/src/main/resources/application.yml

📋 이슈 번호
- #14
- #15 
🛠 구현 사항
- 리마인더 년/월 필터 입력값 유효한지 체크
- 회원가입 시 프로필 자동생성
📚 기타

[Feat] 년/월 필터 Validation / 가입 프로필 자동생성

---

favor/build.gradle
favor/src/main/java/com/favor/favor/anniversary/Anniversary.java
favor/src/main/java/com/favor/favor/anniversary/AnniversaryRequestDto.java
favor/src/main/java/com/favor/favor/anniversary/AnniversaryService.java
favor/src/main/java/com/favor/favor/auth/CustomUserDetailService.java
favor/src/main/java/com/favor/favor/friend/Friend.java
favor/src/main/java/com/favor/favor/friend/FriendController.java
favor/src/main/java/com/favor/favor/friend/FriendService.java
favor/src/main/java/com/favor/favor/friend/account/FriendUserRequestDto.java
favor/src/main/java/com/favor/favor/friend/noAccount/FriendRequestDto.java
favor/src/main/java/com/favor/favor/gift/Gift.java
favor/src/main/java/com/favor/favor/gift/GiftController.java
favor/src/main/java/com/favor/favor/gift/GiftRepository.java
favor/src/main/java/com/favor/favor/gift/GiftRequestDto.java
favor/src/main/java/com/favor/favor/gift/GiftService.java
favor/src/main/java/com/favor/favor/reminder/Reminder.java
favor/src/main/java/com/favor/favor/reminder/ReminderRequestDto.java
favor/src/main/java/com/favor/favor/reminder/ReminderResponseDto.java
favor/src/main/java/com/favor/favor/reminder/ReminderService.java
favor/src/main/java/com/favor/favor/user/ProfileDto.java
favor/src/main/java/com/favor/favor/user/SignDto.java
favor/src/main/java/com/favor/favor/user/SignInResponseDto.java
favor/src/main/java/com/favor/favor/user/User.java
favor/src/main/java/com/favor/favor/user/UserController.java
favor/src/main/java/com/favor/favor/user/UserRepository.java
favor/src/main/java/com/favor/favor/user/UserResponseDto.java
favor/src/main/java/com/favor/favor/user/UserService.java
favor/src/main/java/com/favor/favor/user/UserUpdatePasswordRequestDto.java
favor/src/main/java/com/favor/favor/user/UserUpdateRequestDto.java

- #13 
이전에 임시로 member 디렉토리로 이름을 변경하였는데,
이후 중복된 디렉토리 문제가 해결된 것으로 판단하여 refactor를 진행하였고,
문제없이 동작됨을 확인하였습니다

[Style] User 디렉토리 재구성

---

favor/src/main/java/com/favor/favor/anniversary/AnniversaryController.java
favor/src/main/java/com/favor/favor/friend/FriendController.java
favor/src/main/java/com/favor/favor/gift/GiftController.java
favor/src/main/java/com/favor/favor/reminder/ReminderController.java
favor/src/main/java/com/favor/favor/user/UserController.java

#33 
- Swagger 명세에서 정상 실행의 경우 나타내는 Response Model의 불일치 현상을 수정하였습니다 (확인 필요)
- 현재 DTO 중 예시 값이 존재하지 않는 경우가 있어, 예시 값을 넣어야하는 범위를 조사하여 추가하는 작업이 필요해보입니다.

[Fix] DTO Response Model 재정의

---

favor/src/main/java/com/favor/favor/auth/CustomUserDetailService.java
favor/src/main/java/com/favor/favor/gift/GiftController.java

- #28 
- - GiftController의 @Log4j2를 놓쳤습니다. 이슈 reopen 했습니다.

[Style] Logging tools 통일

---

favor/src/main/java/com/favor/favor/auth/JwtAuthenticationFilter.java
favor/src/main/java/com/favor/favor/configuration/SecurityConfiguration.java
favor/src/main/java/com/favor/favor/gift/GiftController.java

- #34 
`JwtTokenProvider` 
- `secretKey = Base64.getEncoder()` 부분 수정
- `getUserEmail` 수정
- `validateToken` 수정
`SecurityConfiguration`
- `configure(HttpSecurity http)` 수정
- `WebSecurityConfigurerAdapter` 상속 삭제
- 정상작동 확인하였습니다.

[Fix] Deprecated 코드 제거

---

favor/src/main/java/com/favor/favor/friend/FriendController.java
favor/src/main/java/com/favor/favor/friend/FriendResponseDto.java
favor/src/main/java/com/favor/favor/friend/FriendService.java
favor/src/main/java/com/favor/favor/gift/GiftRepository.java
favor/src/main/java/com/favor/favor/user/UserController.java
favor/src/main/java/com/favor/favor/user/UserResponseDto.java
favor/src/main/java/com/favor/favor/user/UserService.java

- #43 
| 기존 회원 DTO | 기존 친구 DTO |
|---|---|
| ![20230620171527](https://github.com/Favor-Gift-Reminder/Favor-Server/assets/114793764/db442c52-227c-41fc-89b9-324132b746e0) | ![20230620172358](https://github.com/Favor-Gift-Reminder/Favor-Server/assets/114793764/d375d2b3-204a-4f2e-9566-9199490f4b5a) |
<br>
| 변경 회원 DTO | 변경 친구 DTO |
|---|---|
| ![20230620172128](https://github.com/Favor-Gift-Reminder/Favor-Server/assets/114793764/def2a7b1-a299-457a-b257-70071e11ac84) | ![20230620172231](https://github.com/Favor-Gift-Reminder/Favor-Server/assets/114793764/cc507def-5867-426e-a50a-733a65dbfeb2) |4f2e-9566-9199490f4b5a) |
<br>
| 회원 전체 선물 조회 | 친구 전체 선물 조회 |
|---|---|
| ![20230620172155](https://github.com/Favor-Gift-Reminder/Favor-Server/assets/114793764/86d00a1d-d87e-49b7-be55-411a5fbf6b5a) | …

[Feat] 친구, 유저 response DTO 수정 / 선물목록 API 구현

---

favor/src/main/java/com/favor/favor/FavorApplication.java
favor/src/main/java/com/favor/favor/anniversary/AnniversaryController.java
favor/src/main/java/com/favor/favor/anniversary/AnniversaryResponseDto.java
favor/src/main/java/com/favor/favor/anniversary/AnniversaryService.java
favor/src/main/java/com/favor/favor/gift/GiftController.java
favor/src/main/java/com/favor/favor/gift/GiftResponseDto.java
favor/src/main/java/com/favor/favor/gift/GiftService.java
favor/src/main/java/com/favor/favor/gift/GiftUpdateRequestDto.java
favor/src/main/resources/application.yml

- #37 
| 수정 후 기념일 DTO | 수정 후 선물 DTO |
| --- | --- |
| ![20230620192653](https://github.com/Favor-Gift-Reminder/Favor-Server/assets/114793764/b200379b-f459-42d2-a2a8-fdd0513ab4c6) | ![20230620192716](https://github.com/Favor-Gift-Reminder/Favor-Server/assets/114793764/b02bd521-7307-4aa8-96a7-7739cd4c9484) |
<br>
| 기념일 핀 여부 수정 | 선물 핀 여부 수정 |
| --- | --- |
| ![20230620192759](https://github.com/Favor-Gift-Reminder/Favor-Server/assets/114793764/c9940005-c49f-40a6-9f1a-f344a0ab7ff3) | ![20230620192736](https://github.com/Favor-Gift-Reminder/Favor-Server/assets/114793764/97c30073-b8d9-48db-beb5-aa5fdd71bd1c) |
| ![20230620192804](https://github.com/Favor-Gift-Reminder/Favor-Server/assets/114793764/9e489e94-f597-4b52-9f7a-2bac85b08f2a) | …

[Feat] 고정 여부 수정 API 구현

---

favor/src/main/java/com/favor/favor/friend/FriendController.java
favor/src/main/java/com/favor/favor/friend/FriendService.java

- FriendService.readTotalGiftList 의 URL 수정
- findGiftByGiftNo 복구
- findGiftListByFriendNo 복구
- returnGiftInfo 복구
- returnDto 수정

[Fix] 피드백 반영 #00

---

favor/src/main/resources/application-dev.yml
favor/src/main/resources/application-prod.yml
favor/src/main/resources/application.yml

close #51
기존의 배포 방식에서 환경설정 파일 (application.yml) 을 가져와야만 배포를 할 수 있는 상태를 개선하기 위해,
prod, dev 환경에서의 환경설정 파일을 새로 생성 후, application,yml에서 원하는 환경을 active하여 실행파일 생성 혹은 서버 실행이 가능하도록 구현하였습니다
15기 서버 스터디 레포 resources 참고

[Style] 배포 간소화를 위한 환경설정 개선 - #51

---

favor/src/main/java/com/favor/favor/anniversary/AnniversaryController.java
favor/src/main/java/com/favor/favor/auth/CustomUserDetailService.java
favor/src/main/java/com/favor/favor/auth/JwtTokenProvider.java
favor/src/main/java/com/favor/favor/configuration/SwaggerConfiguration.java
favor/src/main/java/com/favor/favor/friend/FriendController.java
favor/src/main/java/com/favor/favor/gift/GiftController.java
favor/src/main/java/com/favor/favor/reminder/ReminderController.java
favor/src/main/java/com/favor/favor/user/UserController.java
favor/src/main/java/com/favor/favor/user/UserService.java

close #32 
- @AuthenticationPrincipal 어노테이션을 사용해 기존 uri에서 로그인한 사용자 식별자 (이하 userNo) 를 받아오는 방법 대신 유저 정보 전체를 가져오는 방식으로 변경

[Feat] URI 간소화

---

favor/src/main/java/com/favor/favor/user/UserController.java

received-gifts, given-gifts에 대한 uri에 userNo가 있었던 부분 수정

[Fix] URI 간소화 수정

---

favor/src/main/java/com/favor/favor/user/UserService.java

- UserService.isRightPassword 비밀번호 오류시 예외처리 수정

[Fix] 비밀번호 오류시 예외처리 수정

---

favor/src/main/java/com/favor/favor/anniversary/Anniversary.java
favor/src/main/java/com/favor/favor/friend/Friend.java
favor/src/main/java/com/favor/favor/friend/FriendRequestDto.java
favor/src/main/java/com/favor/favor/friend/FriendResponseDto.java
favor/src/main/java/com/favor/favor/friend/FriendService.java
favor/src/main/java/com/favor/favor/gift/Gift.java
favor/src/main/java/com/favor/favor/reminder/Reminder.java
favor/src/main/java/com/favor/favor/reminder/ReminderController.java
favor/src/main/java/com/favor/favor/user/User.java
favor/src/main/java/com/favor/favor/user/UserController.java
favor/src/main/java/com/favor/favor/user/UserService.java
favor/src/main/java/com/favor/favor/user/UserUpdatePasswordRequestDto.java
favor/src/main/java/com/favor/favor/user/UserUpdateRequestDto.java
favor/src/main/resources/application-dev.yml
favor/src/main/resources/application.yml

- close #59 
- close #58 
FriendResponseDto 의
List<Long> anniversaryNoList
-> List<AnniversaryResponseDto> anniversaryList 로 변경
| 수정 전 | 수정 후 |
| --- | --- |
| ![20230711204840](https://github.com/Favor-Gift-Reminder/Favor-Server/assets/114793764/02b2f0be-27d2-42d6-af4c-272161102a6d) | ![20230711204257](https://github.com/Favor-Gift-Reminder/Favor-Server/assets/114793764/7fb4c473-a2c5-448c-9723-3394561e219b) |
<br><br>
passward 수정 시 encrypt 진행하여 정상적으로 적용되는 것 확인
| 수정 전 | 수정 후 |
| --- | --- |
| ![20230711205458](https://github.com/Favor-Gift-Reminder/Favor-Server/assets/114793764/ba875354-e21d-41ef-9969-137b1ddde9a4) | ![20230711204341](https://github.com/Favor-Gift-Reminder/Favor-Server/assets/114793764/59cd6aab-5d1b-48ba-bdd7-85ac772a2ff6) |
| …

[Fix] 버그 수정, 응답요청 변경

---

.github/workflows/gradle-cicd.yml

[Fix] CI/CD 파이프라인 수정

---

.github/workflows/gradle-cicd.yml

[Fix] CI/CD 파이프라인 수정 - #56

---

.github/workflows/gradle-ci.yml
.github/workflows/gradle-cicd.yml
favor/build.gradle

close #56 
- Jib를 통한 컨테이너 빌드
- github actions in pr, push 구현

[Feat] CI/CD 파이프라인 워크플로우 구현 - #56

---

.github/workflows/gradle-ci.yml
.github/workflows/gradle-cicd.yml

#56
- workflow가 동작하도록 문법에 맞게 수정 진행

[Fix] workflow 문법에 맞게 수정 - #56

---

.github/workflows/gradle-cicd.yml
favor/.gitignore
favor/build.gradle

#56
- gradle ci cd workflow에서 jib가 동작하지 않는 문제를 해결하였습니다

[Fix] jib dockerhub account 설정 - #56

---

.github/workflows/gradle-ci.yml
.github/workflows/gradle-cicd.yml
favor/build.gradle

#56
- 워크플로우의 설정 수정
- 컨테이너 빌드 설정 수정

[Fix] workflow 및 컨테이너 빌드 설정 수정 - #56

---

favor/src/main/java/com/favor/favor/gift/GiftService.java

- close #75 
- 임시리스트 생성으로 Exception 해결

[Fix] 임시 리스트 생성

---

favor/src/main/java/com/favor/favor/friend/FriendService.java
favor/src/main/java/com/favor/favor/user/UserService.java

- close #79 
- UserService.readFriendList 내의 stream 수정
| 수정 전 | 수정 후 | 
| :---: | :---: |
| ![20231116212758](https://github.com/Favor-Gift-Reminder/Favor-Server/assets/114793764/cdf1a16e-882a-40c9-aba0-cdb683e04c33) | ![20231116212626](https://github.com/Favor-Gift-Reminder/Favor-Server/assets/114793764/b957ba07-cb26-409b-b498-cefb649d66ca) |

[Fix] 회원 친구목록 조회 시 잘못된 정보 불러오는 문제

---

favor/src/main/java/com/favor/favor/reminder/ReminderService.java
favor/src/main/java/com/favor/favor/reminder/ReminderUpdateRequestDto.java

- close #81 
- 리마인더 수정 DTO에 friendNo 필드 추가
- null 값 입력 가능하게 구현
| friendNo 필드 추가 | friendNo 미입력시 | 
| :---: | :---: |
| ![20231118235647](https://github.com/Favor-Gift-Reminder/Favor-Server/assets/114793764/dbf5a631-bd44-459d-8f08-5388cd4d3ecd)  | ![20231118235702](https://github.com/Favor-Gift-Reminder/Favor-Server/assets/114793764/4de45d77-38ea-4bd5-aaa3-42392cef130c) | 
| => 친구정보 변경 | => 친구 정보 삭제 |  
| ![20231118235723](https://github.com/Favor-Gift-Reminder/Favor-Server/assets/114793764/410fa0a3-bc6b-4178-8b03-537c883dee87) | ![20231118235708](https://github.com/Favor-Gift-Reminder/Favor-Server/assets/114793764/bdb9106f-0a19-4071-a57f-79f813b9b9a0) |

[Fix] 리마인더 수정 시 친구 정보 추가

---

favor/src/main/java/com/favor/favor/reminder/ReminderService.java
favor/src/main/java/com/favor/favor/reminder/ReminderUpdateRequestDto.java

- close #83 
- 리마인더 생성과 수정 String pattern 동일하게 수정
| 리마인더 생성 | 리마인더 수정 | 
| :---: | :---: |
| ![20231119010154](https://github.com/Favor-Gift-Reminder/Favor-Server/assets/114793764/43ed4015-c74c-4123-b917-1ee29ea08f4f) | ![20231119010214](https://github.com/Favor-Gift-Reminder/Favor-Server/assets/114793764/9f247bbe-bed0-4ba4-8a60-55c73dade04b) |  
| ![20231119010200](https://github.com/Favor-Gift-Reminder/Favor-Server/assets/114793764/24a92abf-90a5-4bcf-8889-39eb04067bb5) | ![20231119010218](https://github.com/Favor-Gift-Reminder/Favor-Server/assets/114793764/ec5f4812-43c6-43fc-847a-f7bcb9ab6ba6) |

[Fix] 리마인더 생성과 수정 String pattern 불일치 문제

---

favor/src/main/java/com/favor/favor/friend/FriendResponseDto.java

유저 조회 응답 DTO의 형태처럼 친구 조회에서 백그라운드 사진 + 프로필 사진을 응답하도록 변경하였습니다
내부 로직 좀 뜯어고치자...

[Fix] 친구 조회 응답 DTO에 백그라운드 사진 추가

---

favor/src/main/java/com/favor/favor/friend/FriendService.java
favor/src/main/java/com/favor/favor/friend/FriendSimpleDto.java
favor/src/main/java/com/favor/favor/gift/GiftService.java
favor/src/main/java/com/favor/favor/reminder/ReminderService.java
favor/src/main/java/com/favor/favor/user/UserController.java
favor/src/main/java/com/favor/favor/user/UserService.java

[Fix] 유저간 아이디(닉네임) 중복 허용 문제, 고유값 추가

---

favor/src/main/java/com/favor/favor/reminder/ReminderSimpleDto.java

- close #91 
- ReminderSimpleDto 에 알람 날짜, 시간 추가

[FIx] ReminderSimpleDto alarm 값 추가
